# Generated by Django 5.0.6 on 2024-06-07 14:17
# and manualy edited by me to replace default '2019-01-02' instead of just '2019' witch is not valid date

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(default='2019-01-02', verbose_name='Date of birth'),
            preserve_default=False,
        ),
    ]
