# Generated by Django 5.0.6 on 2024-06-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equines', '0002_person_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='equine',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
