# Generated by Django 5.0.6 on 2024-06-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equines', '0003_equine_picture_url_person_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equines.person')),
            ],
            bases=('equines.person',),
        ),
        migrations.AlterField(
            model_name='equine',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_horses', to='equines.person'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='equines.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equines.equine')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equines.person')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples', to='equines.lesson')),
            ],
        ),
    ]
