# Generated by Django 5.0.6 on 2024-06-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equines', '0004_instructor_alter_equine_owner_lesson_couple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couple',
            old_name='lessons',
            new_name='lesson',
        ),
    ]
