# Generated by Django 5.0.6 on 2024-06-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equines', '0005_rename_lessons_couple_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equines.person')),
            ],
            bases=('equines.person',),
        ),
    ]
