# Generated by Django 5.1.7 on 2025-03-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equines', '0007_rename_equine_couple_equine_remove_couple_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equines.equine')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='equines.lesson')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equines.rider')),
            ],
        ),
        migrations.DeleteModel(
            name='Couple',
        ),
    ]
